### ISSUE TITLE
Can i ask question about your code here?

### ISSUE THREAD

**Issue by seanexplus** [gaeaplus/gaeaplus#1]
I've clone your source code on github and try to run these examples, but i get some error messages. After modified some code  , i made the sunlight & slope layer function running successfully, but others glsl related function still had problem......

**Comment by gberginc** [comment]
@seanexplus could you please paste the error log here for us to see? If possible, send the entire log produced when you initiate with ant run.

**Comment by seanexplus** [comment]
For example:

I have to remove the first line in your TerrainNormal.glsl, or i can't make the shader compiled correctly.
#version 150 compatibility

Others problems like saving & reading heightmap without using file lock.....

**Comment by seanexplus** [comment]
There are some chinese character in the log, please don't mind^^>
error log 1:

七月 16, 2013 11:31:00 上午 si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
資訊: Compiling shader: file:/D:/work/gaeaplus/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/TerrainNormal.glsl
Shader source:
七月 16, 2013 11:31:00 上午 si.xlab.gaea.core.shaders.BasicGLSLCompiler checkShaderError

1: #define v110
2: #define v120
3: #define v130
4: #define v140
5: #define v150
SEVERE: Error compiling the shader: ERROR: 6:1: '' : syntax error: only other token than #version are permitted after first one

error log 2:

七月 16, 2013 11:34:28 上午 si.xlab.gaea.core.layers.elev.HeightMapLayer$RequestNormalsTask run
WARNING: Deleted corrupted data file file:/C:/ProgramData/Application%20Data/WorldWindData/HeightMapLayer/7/484/484_694png
七月 16, 2013 11:34:28 上午 si.xlab.gaea.core.layers.elev.HeightMapLayer$RequestNormalsTask loadTexture
SEVERE: HeightMapLayer.ExceptionAttemptingToReadFile, URL:file:/C:/ProgramData/Application%20Data/WorldWindData/HeightMapLayer/7/484/484_694png
java.io.EOFException
    at java.io.DataInputStream.readInt(DataInputStream.java:392)
    at java.io.DataInputStream.readFloat(DataInputStream.java:446)
    at si.xlab.gaea.core.layers.elev.HeightMapLayer$RequestNormalsTask.loadTexture(Unknown Source)
    at si.xlab.gaea.core.layers.elev.HeightMapLayer$RequestNormalsTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

**Comment by gberginc** [comment]
We will have a look and get back to you with results. From what I understand the shader requires a shader version that is not supported on your graphics card. Would you mind checking the content of the file in your error log 2 (C:/ProgramData/Application%20Data/WorldWindData/HeightMapLayer/7/484/484_694png)?

**Comment by seanexplus** [comment]
About the first shader problem, my machine is using nvidia geforce gt 635m, the supported glsl version from jogl2 is 400.

The heightmap layer data problem.....from what i saw in the code , the program read current dtm data, then save these data in plain binary float format into files, so i don't know what to check, the value of dtm or eof problem?

**Comment by vcucek** [comment]
We have lowered requirements for default effects to shader 1.20 version.
Some other bugs have been fixed, like HeightMapLayer problem. We have also improved KML shading, shadows, z-buffer-fighting, heightmap preloading, GPU compatibility checking and others.
New fixed gaeaplus will be avaiable in a few days. I still have to test some functionality before commit.
Thank you all for taking the time to report those bugs.

**Comment by gberginc** [comment]
@seanexplus have you tried the latest code? Do you still have problems running the code?
